options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Execute unit tests
  # - name: 'gcr.io/cloud-builders/npm'
  #   args: ['run', 'test']
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chillinker:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chillinker:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chillinker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chillinker:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
images:
  - 'gcr.io/$PROJECT_ID/chillinker:$COMMIT_SHA'
